doc/api_changes/2014-09-04-constants.rst, doc/conf.py, doc/index.rst, doc/resource/api/calibration.rst, doc/resource/api/constants.rst, doc/resource/api/core.rst, doc/resource/api/fitting/model/background.rst, doc/resource/api/fitting/model/physics_peak.rst, doc/resource/api/image.rst, doc/resource/api/io/binary.rst, doc/resource/api/io/index.rst, doc/resource/api/io/spec_to_skxray.rst, doc/resource/api/recip.rst, doc/resource/api/spectroscopy.rst, doc/resource/dev_guide/adding_files.rst, skxray/tests/test_calibration.py
Sundry changes to sphinx source
=> Doc update

skxray/core.py
Need these to make VTTools happy (other wise the parsing of the output goes badly).
=> DOC : make sure outputs have names

skxray/dpc.py
added `()` to help readability, everything else is whitespace
=> PEP8 : whitespace cleanup

setup.py
Actually install the data files
=> WIP : fix install

skxray/cdi.py, skxray/tests/test_cdi.py
Basic functions for Shrinkwrap algorithm in CDI is included in this PR. The aim of the current CDI code is for both 2D and 3D reconstruction.
As CSX will have data soon for image retrieval, CDI method needs to be ranked in high priority, per @stuwilkins 's request. I break the whole task into smaller PRs, and will send them soon.
=> CDI shrinkwrap

skxray/fitting/base/parameter_data.py, skxray/fitting/xrf_model.py, skxray/tests/test_xrf_fit.py
=> Param correction

skxray/img_proc/__init__.py, skxray/img_proc/mathops.py, skxray/tests/test_img_proc.py
This PR focuses exclusively on tools that are being added to facilitate image arithmetic. There are three major functions included in this PR which facilitate image processing using the VisTrails workflow manager. These tools are: 
- arithmetic_basic
- arithmetic_custom
- logic_basic
arithmetic_basic enables easy manipulation of (a) two arrays, (b) two constants, or (c) an array and a constant. The arithmetic operations included in this function are addition, subtraction, multiplication and division. The only serious restriction included as a part of the function is the generation of a ValueError if an array or constant is being divided by 0 (zero).
arithmetic_custom enables more complex arithmetic using up to 8 input arrays or constants. This function allows the user to specify a custom …
=> Image processing: image arithmetic and logic tools

skxray/fitting/xrf_model.py, skxray/tests/test_xrf_fit.py
Fix a bug in test file due to API change on Friday.
=> BUG/TST: linear_spectrum_fitting function in test file

.travis.yml, skxray/recip.py
from pixel position to Q, using pyFAI's calibration/geometry object, also PEP8
=> ENH: add support for XPD reciprocal space translation 

.gitignore, README.md, contributing.txt
=> Add quick start guide and note about testing

conda-recipe/meta.yaml
=> change to 0.8.3

.travis.yml
=> Use scipy=0.15.1

contributing.txt
1) Updated reference: Nikea to scikit-xray
2) Instructions on cloning using https option
3) Instructions for fetching upstream
=> Contribution

README.md
- coveralls service has been intermittent recently
- gitter is cool and we should make more use of it
=> Remove coveralls badge and add gitter badge

README.md
=> noting upcoming name change

README.md
Probably someone beat me to this. :(
=> Suggest new name scikit beam

.travis.yml, skxray/core/fitting/tests/test_xrf_fit.py, skxray/core/recip.py, skxray/core/tests/test_correlation.py, skxray/core/utils.py, skxray/tests/test_openness.py
- backing out changes to the .travis.yml file that disabled running tests.  
- fixing up new tests that were failing because we missed that the tests were not being run.  
- turning on python 3.5 on travis
=> Fixing up the skxray test suite.  It was not actually running on travis

skxray/core/correlation.py, skxray/core/tests/test_correlation.py
The new function is a modified copy of multi_tau_auto_corr function. It supports partial data input when calculation correlation. Each iteration takes previous results.
=> added multi_tau_auto_corr_partial_data function

skbeam/core/dpc.py, skbeam/core/tests/test_dpc.py
Still need to make an example notebook with this code.
=> ENH: Convert DPC code into a generator that operates on partial results

conda-recipe/meta.yaml, setup.py, skbeam/core/recip.py, skbeam/core/utils.py
~~Don't merge this until I know it is building windows skbeam properly~~ ready to go
[edit] updated on 2/22/16
=> MNT: Allow conda binaries for windows to be produced

setup.py, skbeam/core/recip.py, skbeam/core/tests/test_utils.py, skbeam/core/utils.py, src/ctrans.c, src/ctrans.h
This request converts the c routines to use OpenMP (as opposed to pthreads) and uses scatter gather for the grinder.
=> Convert reciprocal space and 3d grinder to OpenMP

skbeam/core/correlation.py
The reference was wrong, I think if fixed it in all places.
=> DOC: Fixed reference

skbeam/core/constants/tests/test_xrf.py, skbeam/core/constants/xrf.py
change xraylib function to output cs in barns.
=> Unit change in xrf cross section

skbeam/core/utils.py, src/ctrans.c, src/ctrans.h
This is currently a WIP but this is an effort to allow partial and sequential clunking of the data. Please do not merge yet
=> ENH: Updates to allow sequential processing

.travis.yml, skbeam/core/tests/test_utils.py, skbeam/core/utils.py
Now supporting masks and any statistic desired. Also uses auto binning if bins not stated.
=> ENH: better circular average

skbeam/core/accumulators/binned_statistic.py, skbeam/core/accumulators/tests/test_binned_statistic.py
Rebase / cherry pick of the code in #446 
attn @chrisvam
=> Binstat cp

skbeam/core/roi.py, skbeam/core/tests/test_roi.py, skbeam/core/utils.py
@yugang is a little busy, here is the update after discussing with him. 
I forked his branch into my repository and made some modifications.
@CJ-Wright @danielballan @tacaswell  (please include any others)
This is regarding PR #459 
Changes:
- removed bin_1D as @sameera2004 's suggestion.
- removed an else statement 
- added a test for the masking
=> Masking added to circular average as an option

skbeam/core/mask.py, skbeam/core/tests/test_mask.py
=> ENH: Add edge and ring blur masks to scikit-beam

skbeam/core/accumulators/binned_statistic.py, skbeam/core/accumulators/tests/test_binned_statistic.py
modified the origin of detector, as mentioned in #466 (most recent comment), discussion with @chrisvam, @ericdill 
thanks!
=> modified origin default

.travis.yml, ci/condarc
Looking at the logs on travis it is not necessarily clear where packages are
coming from. Additionally, we should be using conda-forge to pull packages.
Let's see how this goes...
=> WIP: Use explicit condarc for travis

skbeam/core/image.py
(minor fix) oops, this line is unnecessary, may avoid future confusion
=> removed an unnecessary line

doc/index.rst, skbeam/core/arithmetic.py, skbeam/io/net_cdf_io.py
In the process of reading through the codebase to remind myself what's in it, I wrote a one-sentence summary of each module and added it in the index. It's not polished, but neither are some of our modules.
=> DOC: Include API docs for more of the modules

skbeam/core/accumulators/binned_statistic.py
=> ENH: allow for changing statistic via call

skbeam/core/accumulators/binned_statistic.py
fixes issue with `std_` reference
@danielballan
=> fixed std bug

README.md
I've removed the spaced which 'destroyed' the links.
=> Made links work

skbeam/core/constants/xrf.py, skbeam/core/fitting/tests/test_xrf_fit.py, skbeam/core/fitting/xrf_model.py
Completed k lines are included. Although cross section values for some of the k lines are zero most of the time, it is better to add those lines to achieve better accuracy. Per request by hxn.
=> Add k lines

skbeam/core/roi.py
added a see also
also PEP8 line fix for another line
=> added See Also to segmented_rings

.travis.yml, skbeam/io/tests/test_fit2d_save.py
=> ENH: fix test for fit2d

skbeam/core/fitting/tests/test_xrf_fit.py, skbeam/core/fitting/xrf_model.py
=> Move some fitting related functions from pyxrf to skbeam

skbeam/core/accumulators/binned_statistic.py
=> ENH: speed up by caching bincount and argsort

skbeam/core/smoothing.py, skbeam/core/tests/test_smoothing.py
This is to add a 2D Savitzky–Golay filter function in a new module skbeam/core/smoothing.py
@ericdill @danielballan 
#531
=> Add 2D Savitzky–Golay filter

skbeam/core/fitting/base/parameter_data.py
=> Trun element_list to a list of strings

.travis.yml, doc/whats_new.rst
Summary from v0.0.10-v0.0.15
v0.0.15 is for July depolyment
=> DOC: release

.travis.yml
#552 removed the testing of multiple numpy versions. Fixing it here for pip installation.
Also, added OSX to the test matrix.
=> Specify numpy version during the installation; support OSX builds

.github/workflows/docs.yml
Attempt to fix doc deployment: updated version of 'peaceiris' to v3.9.3
=> Fix for document deployment

.github/workflows/publish-pypi.yml, setup.py
The import order needs to be such that the monkey patching happens.
=> BLD: fix sdist build and upload
