scikit-beam/scikit-beam

contributing.txt, skxray/core.py, skxray/demo/__init__.py, skxray/demo/demo_xrf_spectrum.py, skxray/tests/__init__.py, skxray/tests/test_openness.py
I was inspired by https://modelviewculture.com/pieces/gendered-language-feature-or-bug-in-software-documentation.
This PR adds tests to all docstrings in our library to prevent gendered language from leaking in
=> Gendered Language: Feature or Bug in Software Documentation? 

skxray/cdi.py, skxray/tests/test_cdi.py
The radial_grid from core is for 2D case only, so I still keep the _dist function.
=> ENH/TST: optimize CDI code,

skxray/fitting/background.py, skxray/fitting/base/parameter_data.py, skxray/fitting/models.py, skxray/fitting/xrf_model.py, skxray/tests/test_xrf_fit.py
In this PR, I added pileup peaks for fitting. Pileup peak is the combination of two different elemental lines.
=> Pileup peaks added

.travis.yml, MANIFEST.in, conda-recipe/meta.yaml, doc/installation.rst, optional-requirements.txt, requirements.txt, setup.py, skxray/core/constants/basic.py, skxray/core/stats.py, skxray/core/tests/test_stats.py, skxray/core/tests/test_utils.py, skxray/core/utils.py
* Do a little more to isolate parts of the code that require particular dependencies from those that work just fine with numpy alone.
* Add a `requirements.txt `and an `optional-requirements.txt` to clarify dependencies for users.
* Also split essential and optional dependencies in docs.
* Pin the version of lmfit to 0.8.1. We are broken on 0.8.2 and 0.8.3 (latest) and no one has noticed. @licode can you look at this?
=> BLD/CLN: Isolate dependencies.

.travis.yml
This is required because there were breaking changes in lmfit
between minor versions 8 and 9 that our code exposes in lmfit
=> MNT: Pin lmfit to 0.8.3 on travis

skxray/core/accumulators/histogram.pyx
Use uniform numerical dtype for internal floating point numpy arrays in Histogram.  Also clean up unused C-arrays from the cython part.
=> Histogram adjust dtype

README.md
Update to reflect the org name change from scikit-xray to scikit-beam
and the repo name change from scikit-xray to scikit-beam. Note that
there is still a major overhaul needed to rename the skxray python
package to skbeam
=> DOC: update scikit-xray -> scikit-beam

.travis.yml, doc/build_docs.sh, doc/push_docs.sh, doc/tutorial/write_main_index.py
Ugh it is so hard to get the docs to work, since travis only builds and 
pushes the docs if it is on the master branch.  This PR should build the docs
every time on python 3.5 and if the docs fail, then travis will fail.  It will
only push the docs if travis is not building a PR and is on the scikit-beam org.
=> MNT: Gotta make the output folder

.coveragerc, .travis.yml, README.md, run_tests.py
Just listened to a podcast today with the author of the `coverage` package 
who recommends that you invoke coverage via `coverage run <test_script.py`.
This is also what is listed on the home page of the [coverage docs] 
(https://coverage.readthedocs.org/en/coverage-4.0.3/).  The podcast can 
be found [here] (https://coverage.readthedocs.org/en/coverage-4.0.3/)
for those of you that are interested.
=> MNT: Invoke coverage with the 'coverage run`

.travis.yml, doc/example/Makefile
This is something that was requested by @tacaswell because the sphinx
logs spit out a tremendous amount of information that makes it difficult
to examine the logs for test failures.
=> CI: Build docs separately from automated testing.

skbeam/core/accumulators/binned_statistic.py, skbeam/core/accumulators/tests/test_binned_statistic.py
As I discussed previously with Tom, I realized that the binning specification in the RPhiBinnedStatistic and RadialBinnedStatistic was not as flexible as what was underneath in the scipy binned_statistic code.  This PR tries to address that.  Over the course of doing this, it became clear that my inheritance wasn't structured correctly, so I tried to fix that.
There are three things that seem non-ideal to me:
- the way I implement masking (which is not available in scipy.binned_statistic) is imperfect, but it's the best I can see at the moment.  see comments in code
- there are about 10 lines of code that are duplicated in both RPhiBinnedStatistic and RadialBinnedStatistic.  I might be able to fix this with some inheritance or fancy python tricks
- I should test RPhiBinnedStatistic using …
=> Generalize binning

skbeam/core/accumulators/binned_statistic.py
As discussed with Tom, this one line was brought in from scipy binned_statistic to support the fact that "callable" is not available in python 3.1.  That's an old version which we don't need to support.  Removing this line enables more people to use skbeam's binned_statistic because some versions of scipy don't have scipy._lib.six.
=> don't use scipy._lib.six callable

skbeam/core/accumulators/binned_statistic.py, skbeam/core/accumulators/tests/test_binned_statistic.py
I could use this for binnedstat `bin_centers` property to `BinnedStatistic`.
@chrisvam @tacaswell @danielballan 
Saves typing time.
Would this be okay? Overhead should be slight since the calculation is solely in the initial declaration.
thanks!
=> added bin_centers property

skbeam/core/mask.py
I was testing this function and found that if the mask is an array of integers it crashes. The following line fixes the event that the user inputs an integer mask. At the very least, it should be indicated in the documentation that a bool mask is required. Other than that it seems to work (thanks @CJ-Wright )
@CJ-Wright 
( @tacaswell @danielballan )
details:
Basically, in numpy, say you have a mask array, calling:
```python
img[mask]
```
seems to  lead to two very different cases when mask is of dtype bool versus int. The latter can lead to memory errors (if each entry in `mask` is treated as a row rather than a point). I haven't had time to understand it fully, but as far as I can tell, mask being anything other than a np.ndarray of bools seems to lead to inconsistent results.
(for …
=> forced mask to be bool in auto masking

skbeam/core/correlation.py, skbeam/core/tests/test_correlation.py
Here is an initial pass and suggested API of the mask aware spatial correlations. I tried to remake the API into something more user friendly/scalable. The name is `CrossCorrelator` since it is not necessarily restricted to the spatial domain.
Idea is (`img` and `mask` can be a 1D curve):
```python
ccorr = CrossCorrelator(mask.shape, mask=mask, method='symavg')
cimg = ccorr(img)
```
See [pdf](https://github.com/ordirules/notebooks/blob/master/CrossCorrelator.pdf), or alternatively, the [notebook](https://github.com/ordirules/notebooks/blob/master/CrossCorrelator.ipynb) (equations don't show up well for the latter).
Some things to consider:
1. Is `correlation.py` the appropriate place for this code? It's not an accumulator as well, but perhaps should it become one?
2. The routines …
=> Spatial Correlations

skbeam/core/accumulators/binned_statistic.py
Unfortunately, I think the accumulators are broken in the recently-tagged version of scikit-beam.
```python
binner = BinnedStatisticDD(np.ones((5, 5)))
```
hits a circular reference introduced in #482 and leads to a maximum recursion depth error. This clearly indicates a need for more test coverage, which I will add to this PR before it is merged.
This PR include a fix for that bug and a more minor related bug. It also includes an opinionated API change that should be discussed. See commit messages.
=> Critical bug in accumulators

skbeam/core/correlation.py, skbeam/core/tests/test_correlation.py
I met with Mark Sutton and we discussed the CrossCorrelator code. He had a lot of input and useful advice. He wrote some modifications that made the code 40% faster. I went through them and added some comments to help make them easier to understand for a future contrbutor.
*Changes*
1. Used more efficient indexing tricks to index in images
2. Removed the necessity of expanding the image (`fftconvol` does this for free), got rid of `_crop_from_mask`
3. Removed the `wrap` parameter (since `fftconvol` expands the image to speed up computations,
wrapping is not possible). This parameter was never used so it is simply ignored.
4. Modified tests for 2D and 1D `CrossCorrelator`. New code results are identical to old,
with the exception that new code more efficiently wraps the image.
5. Removed …
=> New and improved Cross correlator

skbeam/core/accumulators/binned_statistic.py, skbeam/core/accumulators/tests/test_binned_statistic.py
the shape check should work with lists or tuples (i.e. `(1,2) == [1,2]` will give false for shape checking, we need to change that)
also, I just noticed, there are no tests for RadialBinnedStatistic! I can add some later if no one objects. Could maybe be to this PR too if you feel it's fitting (in a few days). I use this library alot!
=> fixed shape checking, added test

skbeam/core/accumulators/binned_statistic.py, skbeam/core/accumulators/tests/test_binned_statistic.py
Here's something that has been bothering me and @yugangzhang . When binning using `BinnedStatistic`, there is no straightforward reverse transformation from the flattened bin ids back to the bins. Here's a suggested improvement. Add a `binmap` member which computes the reverse transformation.
For example, it allows you to recover the bins from the top two plots in this figure, coming from the `self.xy` member of the bottom plot:
```python
from pylab import *
ion()
from skbeam.core.accumulators.binned_statistic import RPhiBinnedStatistic,\
BinnedStatisticDD
from skbeam.core.utils import radial_grid, angle_grid
shape = np.array([100, 100])
R = radial_grid(shape/2, shape)
Phi = angle_grid(shape/2., shape)
img = R*np.cos(5*Phi)
rs = RPhiBinnedStatistic(img.shape)
res = rs(img)
binmap = …
```
=> ENH: added binmap to binned_statistic

skbeam/core/utils.py
Tries to resolve #516 
syntax should be `.. math::` and not `..math ::`
@ericdill @tacaswell @danielballan 
(Note : i haven't checked docstrings outside of utils.pyyet)
=> Docstrings latex

skbeam/core/accumulators/binned_statistic.py, skbeam/core/accumulators/tests/test_binned_statistic.py
Same idea as #508 .
This is not ready yet. Will be a good opportunity to finally add tests to `RPhiBinnedStatistic`...
Only `r_map` can be overridden but not `phi_map`. We could add it, but I anticipate this to be only useful for the cases of Ewald curvature on 2D data sets.
=> ENH: Added r_map option to RPhiBinnedStatistic

setup.py
Here is a proposed update to install `numpy` and `cython` dependencies required to run `setup.py` in clean environments. This may possibly be failing on conda.
=> PKG: install required dependencies before setup()

skbeam/core/accumulators/binned_statistic.py
quickly explain what `binmap` is a little more to avoid confusion
@CJ-Wright 
(question arose for how to refill a new image with the statistic obtained in binstat.
We may also want to perhaps document `xy`?
```py
from skbeam.core.accumulators.binned_statistic import RPhiBinnedStatistic
import numpy as np
img = np.random.random((100,100))
nbins = 20
rbinstat = RadialBinnedStatistic(img.shape, origin=(50,50), bins=nbins,
range=((1, 9)))#, (0, np.pi)))
res = rbinstat(img, statistic='mean')
new_img = np.zeros_like(img)
xy = rbinstat.xy
w, = np.where((xy > 0)*(xy < nbins+1))
new_xy = xy.ravel()[w]
new_xy -= 1
new_img.ravel()[w] = res[new_xy]
```
)
=> Improve binmap doc

skbeam/core/utils.py
Just changing `]` to `}`to properly use both arguments to the format function
=> Fix format string

.travis.yml, skbeam/core/tests/test_correlation.py
Numpy support version follows minimum of Dask.
Skip numerical unstable test
=> TST: Skip test for numerical unstalbe reason

MANIFEST.in
This is required for conda-forge / conda-build to pick up the license file properly
=> Add LICENSE to manifest file

.travis.yml, skbeam/core/fitting/xrf_model.py
Fix: compatibility with ```lmfit 0.9.13``` (latest version). Non-invasive fix that bypasses evaluation of 'expr' attribute (string that contains expression specifying restrictions on the parameter, which is evaluated by asteval module) of parameters during Model.make_params() function of ```lmfit 0.9.13```. ```lmfit 0.8.3``` does not perform evaluation of 'expr' attributes until ```Model.fit()``` function is called.
=> Compatibility with lmfit 0.9.13

.travis.yml, requirements.txt, skbeam/core/accumulators/tests/test_binned_statistic.py, skbeam/core/fitting/lineshapes.py
The changes are made to improve numerical stability of `gaussian_tail` function. The proposed changes are preventing overflow due to division of the peak area by a very small number (in the order of 1e-308) and are fixing crashing behavior of PyXRF that happens while attempting to compute Compton scattering model for certain scans. 
Requirements had to be changed: SciPy<=1.3.3. The following tests were failing for SciPy 1.4:
- `test_RadialBinnedStatistic`
- `test_RadialBinnedStatistic_rmap`
=> More stable implementation of 'gaussian_tail' function

pyproject.toml, setup.py
- Added a `pyproject.toml` to declare build deps. This causes pip to install build deps before looking at the `setup.py`, which would otherwise have import errors even with `setup_requires=[...]`.
- Fixed the cythonizer glob to not match docs/..., etc.
=> Fix setup.py and pip installation

.gitignore, .travis.yml, skbeam/core/constants/xrf.py
Starting from xraylib v4.0, the functions are raising exception `ValueError` when called with non-existent emission line/element combination. Previous versions printed optional error message and returned 0. In this PR, the respective functions are changed to catch `ValueError` and return 0.
=> Compatibility with xraylib 4.0

skbeam/core/fitting/xrf_model.py
Fixed bug in the implementation of the equation for computing the shape of Gaussian peak. The energy, which defines the position of the peak center, is split into two components: `center` and `delta_center`. The displacement `delta_center` is very small or zero for all peaks except user defined peaks, so the proposed code change influences only the shape of the user peaks.
=> FIX: computation of peak shape (for user defined peaks)

skbeam/core/constants/xrf.py
This PR contains small change that disables very annoying deprecation message displayed when the function `SetErrorMessages(0)` is called to disable error messages with `xraylib` v4.0.0 or higher. Starting with v4.0.0, xraylib is raising exceptions instead of printing error messages and the function `SetErrorMessages` does absolutely nothing and shouldn't be called. On the other hand, if an older version of xraylib is installed, the function should be used to disable unnecessary error messages.
The changes include checking for the version of xraylib and bypass calling of `SetErrorMessages` if the version is higher than v4.0.0.
=> FIX: disable deprecation message when using xraylib v4.0.0 or higher

.flake8, setup.cfg, skbeam/core/cdi.py, skbeam/core/correlation.py, skbeam/core/tests/test_correlation.py
* changed `one_time_from_two_time()` to fairly weight pixel mean in diagonal
* used `np.nanmean()` in case of dropped frames
* handles multiple two-times 
* updated test to include checking on multiple two-time arrays
*  cover both major changes to function
* added one_time calculation to check contrast ratio is unaffected by future change. assumes contrast calculations are already correct for all functions.
In the future, should I branch skbeam for my updates and then fork ?
The tests passed locally so let me know if I need to do anything else before someone is willing to review.
=> fair weights to average in one-time from two-time

skbeam/core/fitting/tests/test_xrf_model.py, skbeam/core/fitting/xrf_model.py
The `get_line_energy` function was modified so that now it returns the actual energy of the emission line, not `a1` line. In the existing implementation, `get_line_energy("Ca_Kb1")` would return the energy for "Ca_Ka1" line.
The function was originally developed for estimation of locations of pileup peaks and the assumption that only 'ka1', 'la1' and 'ma1' lines contribute to pileup peaks seems reasonable. But in practice, the full names of emission lines are encoded into the names of pileup peaks (e.g. "V_Ka1-Co-Ka1") and the correct way to compute the accurate line energies using full emission names. If lines are to be restricted only to 'ka1', 'la1' and 'ma1' lines, it should be done at higher level, not at the level of model setup.
=> Modifications to 'get_line_energy' function.

skbeam/core/correlation.py, skbeam/core/tests/test_correlation.py
Added errors (standard deviation of the mean) for calculating one-time correlation function from two-time correlation function. Made this as optional output, so all the existing code would still work.
=> Adding error bars to one_time_from_two_times 

skbeam/core/fitting/tests/test_xrf_model.py, skbeam/core/fitting/xrf_model.py
Changed representation for the M-line of Tl from `TL_M` to `Tl_M`: `TL_M` is inconsistent with the accepted formatting standard and causes issues in PyXRF.
=> FIX: changed TL_M to Tl_M
